include: package:very_good_analysis/analysis_options.3.0.2.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    always_declare_return_types: false
    sort_constructors_first: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    invalid_assignment: ignore
    